from pyramid.interfaces import IRequest
from pyramid.registry import Registry

def get_current_request() -> IRequest | None: ...
def get_current_registry(context: object | None = None) -> Registry: ...
